from datetime import datetime

def generate_downloadable_report(detected_data):
    """
    PHASE 6 (Enhanced): Converts JSON into a detailed, well-formatted 
    text report using the verified PostgreSQL medicine info.
    """
    lines = []
    
    # --- Report Header ---
    lines.append("=" * 65)
    lines.append("                  MEDICAL PRESCRIPTION REPORT")
    lines.append("=" * 65)
    
    # Add a timestamp so the user knows when it was generated
    current_time = datetime.now().strftime("%Y-%m-%d %I:%M %p")
    lines.append(f"Generated on: {current_time}")
    lines.append("-" * 65)
    lines.append("")
    
    # --- Handle Empty Data ---
    if not detected_data:
        lines.append("No verified medications detected in this scan.")
        lines.append("=" * 65)
        return "\n".join(lines)

    # --- Process Each Item ---
    for i, item in enumerate(detected_data):
        # 1. Get the corrected display text
        name = item.get('medicine_name') or item.get('text', 'Unknown')
        
        if item.get('is_medicine'):
            summary = item.get('summary', 'No summary available.')
            
            # ✅ Pull the description directly from the item dictionary 
            # (This was populated by PostgreSQL in app.py)
            description = item.get('description', 'Medical info not found.')
            
            # Format as a clean, structured block
            lines.append(f"MEDICATION #{i+1} : {name.upper()}")
            lines.append(f"▶ Summary : {summary}")
            
            # Use text wrapping/indentation for longer descriptions
            lines.append(f"▶ Uses    : {description}")
            lines.append("-" * 65)
            
        else:
            # Handle any non-medicine notes that slip through
            lines.append(f"NOTE #{i+1}       : {name}")
            lines.append("-" * 65)

    # --- Report Footer ---
    lines.append("")
    lines.append("DISCLAIMER:")
    lines.append("This report is generated by AI (MediScan Pro) and is intended for")
    lines.append("informational purposes only. It should not replace professional")
    lines.append("medical advice. Please review this with your pharmacist or doctor.")
    lines.append("=" * 65)
    
    return "\n".join(lines)